### ISSUE TITLE
Custom table name

### ISSUE THREAD

**Issue by krnsptr** [rappasoft/laravel-patches#2]
It would be nice to have a configurable table name for the migration.

https://github.com/rappasoft/laravel-patches/blob/87cd753f203c7bf9f37b0bd92a1dc75dfa523c9b/src/Patcher.php#L61

**Comment by rappasoft** [comment]
Sorry, I must have missed this. I'm open to a PR if you have time otherwise I'll add it to my list.

**Comment by rappasoft** [comment]
Took me long enough but I did it.
